{{- $name := printf "%s-web" (include "cg.name" .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "cg.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "cg.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      automountServiceAccountToken: false
      {{- include "cg.podSecurity" . | nindent 6 }}
      containers:
        - name: web
          image: {{ include "cg.image" (list . .Values.web.repository) }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- include "cg.containerSecurity" . | nindent 10 }}
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet: { path: /login, port: http }
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "cg.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /login
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      targetPort: http
